#!/bin/sh

# BRUTEFORCE: rename TotalTerminal -> TotalTerminal.bundle
# why? installer machinery stopped working for me strangely in 1.1.6, without any obvious reason
# reverted back to Packages 1.0.3 with the same issue...
#
# Some OS gods a protecting all *.bundle files under /Applications/TotalTerminal.app
# I guess it is some interference with new MAS AI introduced in 10.6.6
# I saw they do some dirty Spotlight business to register apps with MAS App
rm -rf "/Applications/TotalTerminal.app/Contents/Resources/TotalTerminal.bundle"
mv "/Applications/TotalTerminal.app/Contents/Resources/TotalTerminal" "/Applications/TotalTerminal.app/Contents/Resources/TotalTerminal.bundle"

open "/Applications/TotalTerminal.app"