#!/bin/sh

sleep 2

# the goal here is to relaunch Terminal.app under the right user aka "Mach bootstrap namespace"
# note: we can have multiple users logged in concruently (for fast user switching), each has its own loginwindow process
# in $OUTPUT we will list all loginwindow processes and pick only the one belonging to the currently logged-in user
USERID=`id -u "$USER"`
OUTPUT=`ps -lax | grep '[l]oginwindow.app' | grep "^[ ]*$USERID "`
if [ -n "$OUTPUT" ]; then
  set - $OUTPUT
  PID=$2

  echo "login window user name is \"$USER\" and PID is \"$PID\""

  if [[ -n "$USER" && -n "$PID" ]]; then
    /bin/launchctl bsexec "$PID" /usr/bin/su "$USER" -c "/usr/bin/open /Applications/TotalTerminal.app"
  fi
fi