#!/bin/sh

# shutdown TotalTerminal agent
killall TotalTerminal

# shutdown crash watcher
/usr/bin/killall -SIGINT TotalTerminalCrashWatcher

# finally quit Terminal
/usr/bin/osascript -e 'tell application "Terminal" to quit'

# remove all SIMBL installations
/bin/rm -rf /Library/Application\ Support/SIMBL/Plugins/Visor.bundle
/bin/rm -rf ~/Library/Application\ Support/SIMBL/Plugins/Visor.bundle

# this is just a safety measure, sometimes system probably caches .app bundles in memory
# TotalFinder case: after 1.4.18 update some users got stuck with old version of some plugins (1.4.16), I have no clue how this could have happened
# let's remove all our stuff prior new installation
rm -rf /Applications/TotalTerminal.app
rm -rf /Library/ScriptingAdditions/TotalTerminal.osax

exit 0